project:
  type: website
  output-dir: docs

website:
  site-url: "http://louisteitelbaum.com/"
  favicon: images/rimonim.svg
  title: "Louis Teitelbaum"
  navbar: 
    logo: images/rimonim.svg
    background: light
    foreground: dark
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: https://ds4psych.com
        text: DS4Psych - Book
      - href: blog.qmd
        text: Blog
      - href: bookshelf.qmd
        text: Virtual Bookshelf
      - href: design.qmd
        text: Art
      - href: CV/CV.pdf
        text: CV
format:
  html:
    theme: 
      - lumen
      - custom.scss
    css: styles.css
    toc: true

render:
    - "*.qmd"
    
editor: visual

