project:
  type: website
  output-dir: docs

website:
  title: "Louis Teitelbaum"
  navbar: 
    background: light
    foreground: dark
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

