project:
  type: website
  output-dir: docs

website:
  site-url: https://rimonim.github.io/
  favicon: images/rimonim.svg
  title: "Louis Teitelbaum"
  navbar: 
    logo: images/rimonim.svg
    background: light
    foreground: dark
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: design.qmd
        text: Art and Design
      - href: CV/CV.pdf
        text: CV
format:
  html:
    theme: lumen
    css: styles.css
    toc: true

render:
    - "*.qmd"
    
editor: visual

